###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID vlsi)
#  Generated on:      Wed May 20 02:03:18 2026
#  Design:            gpu
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Pin offsets inferred from set_clock_latency assertions:
set_ccopt_property insertion_delay -pin {cores[0].core_instance_decoder_instance_decoded_alu_arithmetic_mux_reg[0]/CK} 0.152
set_ccopt_property insertion_delay -pin {cores[0].core_instance_decoder_instance_decoded_immediate_reg[0]/CK} 0.298
set_ccopt_property insertion_delay -pin {cores[0].core_instance_decoder_instance_decoded_immediate_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_decoder_instance_decoded_immediate_reg[2]/CK} 0.254
set_ccopt_property insertion_delay -pin {cores[0].core_instance_decoder_instance_decoded_immediate_reg[5]/CK} 0.130
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rs_reg[4]/CK} 0.231
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rs_reg[5]/CK} 0.281
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rs_reg[6]/CK} 0.287
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rs_reg[7]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[0]/CK} 0.292
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[2]/CK} 0.297
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[3]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[4]/CK} 0.298
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[5]/CK} 0.278
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[0].register_instance_rt_reg[7]/CK} 0.243
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].lsu_instance_mem_read_valid_reg/CK} 0.155
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rs_reg[4]/CK} 0.283
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rs_reg[5]/CK} 0.226
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rs_reg[6]/CK} 0.275
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rs_reg[7]/CK} 0.297
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[0]/CK} 0.293
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[2]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[3]/CK} 0.294
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[4]/CK} 0.296
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[5]/CK} 0.264
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[1].register_instance_rt_reg[7]/CK} 0.234
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rs_reg[4]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rs_reg[5]/CK} 0.238
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rs_reg[6]/CK} 0.278
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rs_reg[7]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[0]/CK} 0.276
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[2]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[3]/CK} 0.285
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[4]/CK} 0.298
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[5]/CK} 0.293
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[2].register_instance_rt_reg[7]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rs_reg[4]/CK} 0.148
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rs_reg[5]/CK} 0.214
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rs_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rs_reg[7]/CK} 0.271
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[0]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[2]/CK} 0.298
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[3]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[4]/CK} 0.294
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[5]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[0].core_instance_threads[3].register_instance_rt_reg[7]/CK} 0.299
set_ccopt_property insertion_delay -pin {cores[1].core_instance_decoder_instance_decoded_alu_arithmetic_mux_reg[0]/CK} 0.147
set_ccopt_property insertion_delay -pin {cores[1].core_instance_decoder_instance_decoded_immediate_reg[0]/CK} 0.299
set_ccopt_property insertion_delay -pin {cores[1].core_instance_decoder_instance_decoded_immediate_reg[1]/CK} 0.299
set_ccopt_property insertion_delay -pin {cores[1].core_instance_decoder_instance_decoded_immediate_reg[2]/CK} 0.268
set_ccopt_property insertion_delay -pin {cores[1].core_instance_decoder_instance_decoded_immediate_reg[7]/CK} 0.223
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rs_reg[4]/CK} 0.255
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rs_reg[5]/CK} 0.294
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rs_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rs_reg[7]/CK} 0.290
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[0]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[2]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[3]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[4]/CK} 0.291
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[5]/CK} 0.296
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[0].register_instance_rt_reg[7]/CK} 0.288
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rs_reg[4]/CK} 0.159
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rs_reg[5]/CK} 0.230
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rs_reg[6]/CK} 0.230
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rs_reg[7]/CK} 0.235
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[0]/CK} 0.291
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[1]/CK} 0.292
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[2]/CK} 0.298
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[3]/CK} 0.282
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[4]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[5]/CK} 0.295
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[6]/CK} 0.292
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[1].register_instance_rt_reg[7]/CK} 0.259
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rs_reg[4]/CK} 0.238
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rs_reg[5]/CK} 0.235
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rs_reg[6]/CK} 0.251
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rs_reg[7]/CK} 0.235
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[0]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[2]/CK} 0.295
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[3]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[4]/CK} 0.295
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[5]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[6]/CK} 0.254
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[2].register_instance_rt_reg[7]/CK} 0.291
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rs_reg[4]/CK} 0.162
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rs_reg[5]/CK} 0.160
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rs_reg[6]/CK} 0.296
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rs_reg[7]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[0]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[1]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[2]/CK} 0.298
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[3]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[4]/CK} 0.295
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[5]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[6]/CK} 0.300
set_ccopt_property insertion_delay -pin {cores[1].core_instance_threads[3].register_instance_rt_reg[7]/CK} 0.300
set_ccopt_property insertion_delay -pin {data_memory_controller_channel_serving_consumer_reg[1]/CK} 0.063
set_ccopt_property insertion_delay -pin {dcr_instance_device_control_register_reg[0]/CK} 0.259
set_ccopt_property insertion_delay -pin {dcr_instance_device_control_register_reg[1]/CK} 0.257
set_ccopt_property insertion_delay -pin {dcr_instance_device_control_register_reg[2]/CK} 0.122

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 2.200ns) in timing_config func_mode([/home/user_77/backup_extract/my_project/project/make_flow/DESIGN/init_design.dat/libs/mmmc/constraints_top.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner slow_delay -early -clock_tree clk 0.050
set_ccopt_property target_max_trans_sdc -delay_corner slow_delay -late -clock_tree clk 0.050
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2.2

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:func_mode (sdc /home/user_77/backup_extract/my_project/project/make_flow/DESIGN/init_design.dat/libs/mmmc/constraints_top.sdc)
create_ccopt_skew_group -name clk/func_mode -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/func_mode true
set_ccopt_property extracted_from_clock_name -skew_group clk/func_mode clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/func_mode func_mode
set_ccopt_property extracted_from_delay_corners -skew_group clk/func_mode {slow_delay fast_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

