###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID vlsi)
#  Generated on:      Wed May 20 02:17:04 2026
#  Design:            gpu
#  Command:           saveDesign DESIGN/postRoute
###############################################################
current_design gpu
create_clock [get_ports {clk}]  -name clk -period 2.200000 -waveform {0.000000 1.100000}
set_clock_transition  -rise -min 0.05 [get_clocks {clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {clk}]
set_propagated_clock  [get_ports {clk}]
set_max_capacitance 0.1  [get_designs {gpu}]
set_max_fanout 50  [get_designs {gpu}]
set_max_transition 0.2  [get_designs {gpu}]
set_input_delay -add_delay 0.8 -max -clock [get_clocks {clk}] [get_ports {reset}]
set_output_delay -add_delay 0.8 -max -clock [get_clocks {clk}] [get_ports {done}]
set_clock_uncertainty 0.05 [get_clocks {clk}]
set_false_path  -from [get_ports {reset}] 
